### ISSUE TITLE
Repo still used?

### ISSUE THREAD

**Issue by maoo** [finos/plexus-interop-desktop-api#1]
Hi there!

I see that there haven't been updates on this repo since a long time; is it still used/relevant, or shall we archive it?

Thanks in advance!

**Comment by TheJuanAndOnly99** [comment]
Hi @iskender-kamchibekov-db @alexogar is this repo still relevant? We would like to archive it if not.

Thanks!

**Comment by iskender-kamchibekov-db** [comment]
Hi. I think this repo is outdated but we need some time to know the details to be sure.

**Comment by iskender-kamchibekov-db** [comment]
Let's archive this repo and just unarchive if we need it again.

**Comment by finos-admin** [comment]
Thanks @iskender-kamchibekov-db. Archiving repo.
